-- ============================================================================
-- KURA — Sistema de Gestão Veterinária
-- Cliente: Clyvo Vet (Challenge FIAP 2026)
-- Banco: Oracle 19c+ (parceria FIAP × Oracle — sempre ativo)
-- Notação: 3FN | Constraints nomeadas | Sequences .NET | IDENTITY Java
-- ============================================================================
-- VERSÃO: v5
-- DATA   : 2026-05-21
-- AUTOR  : Felipe Ferrete (tech lead)
--
-- ALTERAÇÕES EM RELAÇÃO À v4:
--   [1] AGENDAMENTO         → colunas Java adicionadas (Flyway V5):
--                             DS_OBSERVACOES, DT_CRIACAO, DT_CONFIRMACAO,
--                             DT_CANCELAMENTO, DS_MOTIVO_CANCEL, ID_EVENTO_GERADO
--                             FK_AGEND_EVENTO → EVENTO_CLINICO
--   [2] CONTA_TUTOR         → coluna DT_CRIACAO (v4 chamava DT_CADASTRO por engano)
--                             sem DS_SALT (não mapeado pela entity Java)
--   [3] CONSENTIMENTO       → campos LGPD incluídos (ANPD evidência art. 7º, I):
--                             DS_TEXTO_TERMO CLOB, DS_IP_ACEITE, DT_REVOGACAO,
--                             DS_IP_REVOGACAO; DT_ACEITE (não DT_CONSENTIMENTO);
--                             DS_VERSAO_TERMO (não NR_VERSAO_TERMO)
--   [4] TUTOR               → DS_TELEFONE (coluna real; v4 tinha NR_TELEFONE);
--                             DT_CADASTRO (coluna real; v4 tinha DT_CRIACAO)
--   [5] RACA                → DS_PREDISPOSICAO VARCHAR2(500) incluída
--   [6] PET                 → campos legados removidos (NR_PESO_KG, ST_CASTRADO,
--                             DS_ALERGIAS, DS_OBSERVACOES — Java entity não mapeia)
--   [7] UK_CONTA_INVITE_USED→ constraint inline (era V3 migration)
--   [8] IDX_INVITE_TOKEN_ATIVO → índice composto inline (era V3 migration)
--   [9] IDX_IDEMPOT_CRIACAO → índice limpeza TTL inline (era V2 migration)
--   [10] VIEWS              → aliases atualizados para V6 (AGENDAMENTO-based)
-- ============================================================================
-- ARQUITETURA DE DOMÍNIOS:
--   .NET (Backend Clínica — Felipe) — escreve:
--       CLINICA, VETERINARIO, TUTOR, PET, ESPECIE, RACA,
--       EVENTO_CLINICO, TIPO_EVENTO, CONSULTA, VACINA, PRESCRICAO,
--       MEDICAMENTO, EXAME, DOCUMENTO, NOTIFICACAO,
--       DISPOSITIVO_IOT, LEITURA_TEMPERATURA, ALERTA_TEMPERATURA,
--       TRIAGEM_LUNA, INVITE_TUTOR, TUTOR_PET
--   Java (Backend Tutor — Nikolas) — escreve:
--       CONTA_TUTOR, CONSENTIMENTO, AGENDAMENTO, IDEMPOTENCY_KEY
--   Leitura cruzada:
--       .NET lê  CONTA_TUTOR, CONSENTIMENTO, AGENDAMENTO
--       Java lê  INVITE_TUTOR, TUTOR, PET, VETERINARIO, CLINICA, ESPECIE, RACA
-- ============================================================================
-- ESTRATÉGIA DE PK:
--   .NET-owned tables   → Oracle sequences (DEFAULT SEQ_xxx.NEXTVAL)
--   AGENDAMENTO         → SEQ_AGENDAMENTO (Java usa GenerationType.SEQUENCE)
--   Java-owned tables   → GENERATED BY DEFAULT AS IDENTITY (Java usa
--                          GenerationType.IDENTITY; Oracle 19c suporta nativamente)
-- ============================================================================

-- ============================================================================
-- 0. LIMPEZA — descomentar e executar antes de re-criar o schema
--    (ordem reversa de dependências)
-- ============================================================================

-- DROP TABLE IDEMPOTENCY_KEY              CASCADE CONSTRAINTS;
-- DROP TABLE CONSENTIMENTO                CASCADE CONSTRAINTS;
-- DROP TABLE CONTA_TUTOR                  CASCADE CONSTRAINTS;
-- DROP TABLE AGENDAMENTO                  CASCADE CONSTRAINTS;
-- DROP TABLE TRIAGEM_LUNA                 CASCADE CONSTRAINTS;
-- DROP TABLE ALERTA_TEMPERATURA           CASCADE CONSTRAINTS;
-- DROP TABLE LEITURA_TEMPERATURA          CASCADE CONSTRAINTS;
-- DROP TABLE DISPOSITIVO_IOT              CASCADE CONSTRAINTS;
-- DROP TABLE NOTIFICACAO                  CASCADE CONSTRAINTS;
-- DROP TABLE DOCUMENTO                    CASCADE CONSTRAINTS;
-- DROP TABLE EXAME                        CASCADE CONSTRAINTS;
-- DROP TABLE PRESCRICAO                   CASCADE CONSTRAINTS;
-- DROP TABLE CONSULTA                     CASCADE CONSTRAINTS;
-- DROP TABLE VACINA                       CASCADE CONSTRAINTS;
-- DROP TABLE EVENTO_CLINICO               CASCADE CONSTRAINTS;
-- DROP TABLE TIPO_EVENTO                  CASCADE CONSTRAINTS;
-- DROP TABLE INVITE_TUTOR                 CASCADE CONSTRAINTS;
-- DROP TABLE TUTOR_PET                    CASCADE CONSTRAINTS;
-- DROP TABLE PET                          CASCADE CONSTRAINTS;
-- DROP TABLE RACA                         CASCADE CONSTRAINTS;
-- DROP TABLE ESPECIE                      CASCADE CONSTRAINTS;
-- DROP TABLE TUTOR                        CASCADE CONSTRAINTS;
-- DROP TABLE VETERINARIO                  CASCADE CONSTRAINTS;
-- DROP TABLE CLINICA                      CASCADE CONSTRAINTS;
-- DROP TABLE MEDICAMENTO                  CASCADE CONSTRAINTS;
-- DROP TABLE LOG_ERRO                     CASCADE CONSTRAINTS;

-- DROP SEQUENCE SEQ_CLINICA;
-- DROP SEQUENCE SEQ_VETERINARIO;
-- DROP SEQUENCE SEQ_TUTOR;
-- DROP SEQUENCE SEQ_ESPECIE;
-- DROP SEQUENCE SEQ_RACA;
-- DROP SEQUENCE SEQ_PET;
-- DROP SEQUENCE SEQ_TIPO_EVENTO;
-- DROP SEQUENCE SEQ_EVENTO_CLINICO;
-- DROP SEQUENCE SEQ_CONSULTA;
-- DROP SEQUENCE SEQ_VACINA;
-- DROP SEQUENCE SEQ_MEDICAMENTO;
-- DROP SEQUENCE SEQ_PRESCRICAO;
-- DROP SEQUENCE SEQ_EXAME;
-- DROP SEQUENCE SEQ_DOCUMENTO;
-- DROP SEQUENCE SEQ_AGENDAMENTO;
-- DROP SEQUENCE SEQ_NOTIFICACAO;
-- DROP SEQUENCE SEQ_LOG_ERRO;
-- DROP SEQUENCE SEQ_DISPOSITIVO_IOT;
-- DROP SEQUENCE SEQ_LEITURA_TEMP;
-- DROP SEQUENCE SEQ_ALERTA_TEMP;
-- DROP SEQUENCE SEQ_TRIAGEM_LUNA;
-- DROP SEQUENCE SEQ_INVITE_TUTOR;

-- DROP VIEW VW_TIMELINE_PET;
-- DROP VIEW VW_VACINAS_VENCENDO;

-- ============================================================================
-- 1. SEQUENCES — tabelas .NET + AGENDAMENTO (Java usa GenerationType.SEQUENCE)
-- ============================================================================

CREATE SEQUENCE SEQ_CLINICA          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VETERINARIO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TUTOR            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ESPECIE          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RACA             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PET              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TIPO_EVENTO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENTO_CLINICO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONSULTA         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VACINA           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDICAMENTO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRESCRICAO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXAME            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOCUMENTO        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AGENDAMENTO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTIFICACAO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOG_ERRO         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DISPOSITIVO_IOT  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LEITURA_TEMP     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTA_TEMP      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRIAGEM_LUNA     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVITE_TUTOR     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================================
-- 2. ENTIDADES INDEPENDENTES (sem FKs)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CLINICA — Domínio: .NET
-- Java lê via entity @Immutable.
-- ----------------------------------------------------------------------------
CREATE TABLE CLINICA (
    ID_CLINICA       NUMBER(10)       DEFAULT SEQ_CLINICA.NEXTVAL NOT NULL,
    NM_CLINICA       VARCHAR2(120)    NOT NULL,
    NR_CNPJ          VARCHAR2(18)     NOT NULL,
    NM_RAZAO_SOCIAL  VARCHAR2(150),
    DS_ENDERECO      VARCHAR2(200),
    NM_CIDADE        VARCHAR2(80),
    SG_UF            CHAR(2),
    NR_CEP           VARCHAR2(9),
    DS_TELEFONE      VARCHAR2(20),
    DS_EMAIL         VARCHAR2(120),
    DS_EMAIL_ACESSO  VARCHAR2(120),
    DS_SENHA_HASH    VARCHAR2(256),
    DT_CADASTRO      TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    ST_ATIVA         CHAR(1)          DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_CLINICA              PRIMARY KEY (ID_CLINICA),
    CONSTRAINT UK_CLINICA_CNPJ         UNIQUE (NR_CNPJ),
    CONSTRAINT UK_CLINICA_EMAIL_ACESSO UNIQUE (DS_EMAIL_ACESSO),
    CONSTRAINT CK_CLINICA_ATIVA        CHECK (ST_ATIVA IN ('S','N'))
);

COMMENT ON TABLE  CLINICA                 IS 'Clínicas veterinárias — .NET owns. Java lê via @Immutable.';
COMMENT ON COLUMN CLINICA.DS_EMAIL_ACESSO IS 'E-mail de login da clínica no painel .NET — UNIQUE.';
COMMENT ON COLUMN CLINICA.DS_SENHA_HASH   IS 'BCrypt hash — NUNCA texto plano. Gerenciado pelo .NET.';
COMMENT ON COLUMN CLINICA.DT_CADASTRO     IS 'Data de criação do registro.';

-- ----------------------------------------------------------------------------
-- ESPECIE — Domínio: .NET | Tabela de lookup (cacheable)
-- Java lê via entity @Immutable (Caffeine cache em EspecieService).
-- ----------------------------------------------------------------------------
CREATE TABLE ESPECIE (
    ID_ESPECIE     NUMBER(10)     DEFAULT SEQ_ESPECIE.NEXTVAL NOT NULL,
    NM_ESPECIE     VARCHAR2(200)  NOT NULL,
    DT_CRIACAO     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT PK_ESPECIE      PRIMARY KEY (ID_ESPECIE),
    CONSTRAINT UK_ESPECIE_NOME UNIQUE (NM_ESPECIE)
);

COMMENT ON TABLE ESPECIE IS 'Tipos de animais: Cão, Gato, Ave, Réptil etc. Cacheable — baixa mutabilidade.';

-- ----------------------------------------------------------------------------
-- MEDICAMENTO — Domínio: .NET | Catálogo central de medicamentos
-- ----------------------------------------------------------------------------
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO     NUMBER(10)     DEFAULT SEQ_MEDICAMENTO.NEXTVAL NOT NULL,
    NM_MEDICAMENTO     VARCHAR2(200)  NOT NULL,
    DS_PRINCIPIO_ATIVO VARCHAR2(500)  NOT NULL,
    DS_APRESENTACAO    VARCHAR2(500)  NOT NULL,
    DT_CRIACAO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO)
);

COMMENT ON COLUMN MEDICAMENTO.DS_PRINCIPIO_ATIVO IS 'Princípio ativo (ex: Oclacitinib).';
COMMENT ON COLUMN MEDICAMENTO.DS_APRESENTACAO    IS 'Apresentação (ex: comprimido 16 mg, frasco 50 ml).';

-- ----------------------------------------------------------------------------
-- TIPO_EVENTO — Domínio: .NET | Tabela de domínio
-- ----------------------------------------------------------------------------
CREATE TABLE TIPO_EVENTO (
    ID_TIPO_EVENTO  NUMBER(5)      DEFAULT SEQ_TIPO_EVENTO.NEXTVAL NOT NULL,
    CD_TIPO         VARCHAR2(20)   NOT NULL,
    NM_TIPO         VARCHAR2(200)  NOT NULL,
    DS_TIPO         VARCHAR2(200),
    ST_ATIVO        CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO  TIMESTAMP,
    CONSTRAINT PK_TIPO_EVENTO    PRIMARY KEY (ID_TIPO_EVENTO),
    CONSTRAINT UK_TIPO_EVENTO_CD UNIQUE (CD_TIPO),
    CONSTRAINT UK_TIPO_EVENTO_NM UNIQUE (NM_TIPO),
    CONSTRAINT CK_TIPO_ATIVO     CHECK (ST_ATIVO IN ('S','N'))
);

COMMENT ON TABLE  TIPO_EVENTO        IS 'Catálogo: CONSULTA, TELEORIENTACAO, VACINA, PRESCRICAO, EXAME, PROCEDIMENTO, RETORNO.';
COMMENT ON COLUMN TIPO_EVENTO.CD_TIPO IS 'Código imutável de negócio (usado pelo .NET EF Core como enum).';

-- ============================================================================
-- 3. ENTIDADES DEPENDENTES — NÍVEL 1
-- ============================================================================

-- ----------------------------------------------------------------------------
-- VETERINARIO — Domínio: .NET | FK CLINICA
-- Java lê via entity @Immutable.
-- ----------------------------------------------------------------------------
CREATE TABLE VETERINARIO (
    ID_VETERINARIO  NUMBER(10)     DEFAULT SEQ_VETERINARIO.NEXTVAL NOT NULL,
    ID_CLINICA      NUMBER(10)     NOT NULL,
    NM_VETERINARIO  VARCHAR2(200)  NOT NULL,
    NR_CRMV         VARCHAR2(20),
    DS_EMAIL        VARCHAR2(150),
    NR_TELEFONE     VARCHAR2(20),
    ST_ATIVO        CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO  TIMESTAMP,
    CONSTRAINT PK_VETERINARIO   PRIMARY KEY (ID_VETERINARIO),
    CONSTRAINT FK_VET_CLINICA   FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_VET_CRMV      UNIQUE (NR_CRMV),
    CONSTRAINT UK_VET_EMAIL     UNIQUE (DS_EMAIL),
    CONSTRAINT CK_VET_ATIVO     CHECK (ST_ATIVO IN ('S','N'))
);

CREATE INDEX IDX_VET_CLINICA ON VETERINARIO(ID_CLINICA);

COMMENT ON TABLE  VETERINARIO       IS 'Veterinários da clínica — .NET owns. Java lê via @Immutable.';
COMMENT ON COLUMN VETERINARIO.NR_CRMV IS 'Número do CRMV (registro profissional).';

-- ----------------------------------------------------------------------------
-- TUTOR — Domínio: .NET (cadastro) | Java lê via @Immutable
-- ATENÇÃO: coluna DS_TELEFONE (não NR_TELEFONE) e DT_CADASTRO (não DT_CRIACAO) —
-- nomes reais conforme Java entity e Flyway V1.
-- ----------------------------------------------------------------------------
CREATE TABLE TUTOR (
    ID_TUTOR              NUMBER(10)     DEFAULT SEQ_TUTOR.NEXTVAL NOT NULL,
    ID_CLINICA            NUMBER(10)     NOT NULL,
    NM_TUTOR              VARCHAR2(200)  NOT NULL,
    NR_CPF                VARCHAR2(11)   NOT NULL,
    DS_EMAIL              VARCHAR2(150)  NOT NULL,
    DS_TELEFONE           VARCHAR2(20)   NOT NULL,
    DS_WHATSAPP           VARCHAR2(20),
    DT_NASCIMENTO         DATE,
    DS_ENDERECO           VARCHAR2(200),
    NM_CIDADE             VARCHAR2(80),
    SG_UF                 CHAR(2),
    NR_CEP                VARCHAR2(9),
    DT_CADASTRO           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO        TIMESTAMP,
    ST_ATIVO              CHAR(1)        DEFAULT 'S' NOT NULL,
    ST_AVISO_PRIVACIDADE  CHAR(1)        DEFAULT 'N' NOT NULL,
    DT_AVISO_PRIVACIDADE  TIMESTAMP,
    DS_VERSAO_AVISO       VARCHAR2(20),
    CONSTRAINT PK_TUTOR          PRIMARY KEY (ID_TUTOR),
    CONSTRAINT FK_TUTOR_CLINICA  FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_TUTOR_CPF      UNIQUE (NR_CPF),
    CONSTRAINT UK_TUTOR_EMAIL    UNIQUE (DS_EMAIL),
    CONSTRAINT CK_TUTOR_ATIVO    CHECK (ST_ATIVO IN ('S','N')),
    CONSTRAINT CK_TUTOR_AVISO    CHECK (ST_AVISO_PRIVACIDADE IN ('S','N'))
);

CREATE INDEX IDX_TUTOR_CLINICA ON TUTOR(ID_CLINICA);

COMMENT ON TABLE  TUTOR                       IS 'Responsável pelo pet. Cadastrado pela clínica (.NET). Conta de acesso = CONTA_TUTOR (Java).';
COMMENT ON COLUMN TUTOR.DS_WHATSAPP           IS 'Número WhatsApp para Luna (bot) — pode coincidir com DS_TELEFONE.';
COMMENT ON COLUMN TUTOR.ST_AVISO_PRIVACIDADE  IS 'S = tutor recebeu aviso de privacidade (transparência LGPD art. 6º VI).';
COMMENT ON COLUMN TUTOR.DS_VERSAO_AVISO       IS 'Versão do aviso apresentado (ex: v1.0, v1.1).';

-- ----------------------------------------------------------------------------
-- RACA — Domínio: .NET | FK ESPECIE
-- Java lê via entity @Immutable (Caffeine cache em RacaService).
-- ----------------------------------------------------------------------------
CREATE TABLE RACA (
    ID_RACA          NUMBER(5)      DEFAULT SEQ_RACA.NEXTVAL NOT NULL,
    ID_ESPECIE       NUMBER(10)     NOT NULL,
    NM_RACA          VARCHAR2(80)   NOT NULL,
    DS_PREDISPOSICAO VARCHAR2(500),
    DT_CRIACAO       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_RACA         PRIMARY KEY (ID_RACA),
    CONSTRAINT FK_RACA_ESPECIE FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID_ESPECIE),
    CONSTRAINT UK_RACA_ESPECIE UNIQUE (NM_RACA, ID_ESPECIE)
);

CREATE INDEX IDX_RACA_ESPECIE ON RACA(ID_ESPECIE);

COMMENT ON TABLE  RACA                IS 'Raças por espécie. Cacheable — baixa mutabilidade.';
COMMENT ON COLUMN RACA.DS_PREDISPOSICAO IS 'Predisposições genéticas da raça (opcional, usada por alertas da Luna).';

-- ============================================================================
-- 4. PET — ENTIDADE CENTRAL
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PET — Domínio: .NET | FKs CLINICA, ESPECIE, RACA, VETERINARIO
-- Java lê via entity @Immutable.
-- ----------------------------------------------------------------------------
CREATE TABLE PET (
    ID_PET               NUMBER(10)     DEFAULT SEQ_PET.NEXTVAL NOT NULL,
    ID_CLINICA           NUMBER(10)     NOT NULL,
    ID_ESPECIE           NUMBER(10)     NOT NULL,
    ID_RACA              NUMBER(5),
    ID_VETERINARIO_RESP  NUMBER(10),
    NM_PET               VARCHAR2(80)   NOT NULL,
    DT_NASCIMENTO        DATE,
    SG_SEXO              CHAR(1),
    SG_PORTE             CHAR(1),
    ST_ATIVO             CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO       TIMESTAMP,
    CONSTRAINT PK_PET             PRIMARY KEY (ID_PET),
    CONSTRAINT FK_PET_CLINICA     FOREIGN KEY (ID_CLINICA)          REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_PET_ESPECIE     FOREIGN KEY (ID_ESPECIE)          REFERENCES ESPECIE(ID_ESPECIE),
    CONSTRAINT FK_PET_RACA        FOREIGN KEY (ID_RACA)             REFERENCES RACA(ID_RACA),
    CONSTRAINT FK_PET_VET_RESP    FOREIGN KEY (ID_VETERINARIO_RESP) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CK_PET_SEXO        CHECK (SG_SEXO  IN ('M','F')),
    CONSTRAINT CK_PET_PORTE       CHECK (SG_PORTE IN ('P','M','G')),
    CONSTRAINT CK_PET_ATIVO       CHECK (ST_ATIVO IN ('S','N'))
);

CREATE INDEX IDX_PET_CLINICA     ON PET(ID_CLINICA);
CREATE INDEX IDX_PET_ESPECIE     ON PET(ID_ESPECIE);
CREATE INDEX IDX_PET_RACA        ON PET(ID_RACA);
CREATE INDEX IDX_PET_VET_RESP    ON PET(ID_VETERINARIO_RESP);

COMMENT ON TABLE  PET                    IS 'Animal atendido. ID_PET = prontuário único do paciente. .NET owns.';
COMMENT ON COLUMN PET.SG_PORTE          IS 'P=Pequeno, M=Médio, G=Grande.';
COMMENT ON COLUMN PET.ID_VETERINARIO_RESP IS 'Veterinário responsável principal — opcional.';

-- ----------------------------------------------------------------------------
-- TUTOR_PET — Domínio: .NET | N:N entre TUTOR e PET
-- ----------------------------------------------------------------------------
CREATE TABLE TUTOR_PET (
    ID_TUTOR     NUMBER(10)    NOT NULL,
    ID_PET       NUMBER(10)    NOT NULL,
    DS_VINCULO   VARCHAR2(50)  DEFAULT 'PROPRIETARIO' NOT NULL,
    ST_PRINCIPAL CHAR(1)       DEFAULT 'S' NOT NULL,
    DT_VINCULO   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TUTOR_PET       PRIMARY KEY (ID_TUTOR, ID_PET),
    CONSTRAINT FK_TP_TUTOR        FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_TP_PET          FOREIGN KEY (ID_PET)   REFERENCES PET(ID_PET),
    CONSTRAINT CK_TP_PRINCIPAL    CHECK (ST_PRINCIPAL IN ('S','N'))
);

CREATE INDEX IDX_TP_PET ON TUTOR_PET(ID_PET);

COMMENT ON TABLE  TUTOR_PET              IS 'Vínculo N:N tutores ↔ pets. Suporta casal compartilhando guarda.';
COMMENT ON COLUMN TUTOR_PET.ST_PRINCIPAL IS 'S = tutor principal (recebe notificações por padrão).';

-- ============================================================================
-- 5. EVENTOS CLÍNICOS — Domínio: .NET
-- ============================================================================

-- ----------------------------------------------------------------------------
-- EVENTO_CLINICO — Tabela-mãe da timeline do pet
-- Java lê indiretamente (AGENDAMENTO.ID_EVENTO_GERADO → aqui).
-- ----------------------------------------------------------------------------
CREATE TABLE EVENTO_CLINICO (
    ID_EVENTO       NUMBER(10)     DEFAULT SEQ_EVENTO_CLINICO.NEXTVAL NOT NULL,
    ID_CLINICA      NUMBER(10)     NOT NULL,
    ID_PET          NUMBER(10),
    ID_VETERINARIO  NUMBER(10),
    ID_TIPO_EVENTO  NUMBER(5),
    DS_DESCRICAO    VARCHAR2(500),
    DT_EVENTO       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DS_OBSERVACAO   VARCHAR2(1000),
    DT_CRIACAO      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO  TIMESTAMP,
    CONSTRAINT PK_EVENTO_CLINICO  PRIMARY KEY (ID_EVENTO),
    CONSTRAINT FK_EV_CLINICA      FOREIGN KEY (ID_CLINICA)     REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_EV_PET          FOREIGN KEY (ID_PET)         REFERENCES PET(ID_PET),
    CONSTRAINT FK_EV_VETERINARIO  FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT FK_EV_TIPO         FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPO_EVENTO(ID_TIPO_EVENTO)
);

CREATE INDEX IDX_EV_CLINICA     ON EVENTO_CLINICO(ID_CLINICA);
CREATE INDEX IDX_EV_PET         ON EVENTO_CLINICO(ID_PET);
CREATE INDEX IDX_EV_VETERINARIO ON EVENTO_CLINICO(ID_VETERINARIO);
CREATE INDEX IDX_EV_TIPO        ON EVENTO_CLINICO(ID_TIPO_EVENTO);
CREATE INDEX IDX_EV_DATA        ON EVENTO_CLINICO(DT_EVENTO DESC);

COMMENT ON TABLE EVENTO_CLINICO IS 'Núcleo da timeline clínica do pet. Cada interação = 1 evento. .NET owns.';

-- ----------------------------------------------------------------------------
-- CONSULTA — Subtipo de EVENTO_CLINICO (1:1)
-- ----------------------------------------------------------------------------
CREATE TABLE CONSULTA (
    ID_CONSULTA        NUMBER(10)     DEFAULT SEQ_CONSULTA.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)     NOT NULL,
    DS_MOTIVO          VARCHAR2(200)  NOT NULL,
    DS_ANAMNESE        VARCHAR2(2000),
    DS_EXAME_FISICO    VARCHAR2(2000),
    DS_DIAGNOSTICO     VARCHAR2(1000),
    DT_CONSULTA        TIMESTAMP      NOT NULL,
    ST_ATIVA           CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_CONSULTA        PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT FK_CONSULTA_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT UK_CONSULTA_EVENTO UNIQUE (ID_EVENTO_CLINICO),
    CONSTRAINT CK_CONSULTA_ATIVA  CHECK (ST_ATIVA IN ('S','N'))
);

COMMENT ON TABLE CONSULTA IS 'Detalhes clínicos de consulta. 1:1 com EVENTO_CLINICO.';

-- ----------------------------------------------------------------------------
-- VACINA — Subtipo de EVENTO_CLINICO
-- ----------------------------------------------------------------------------
CREATE TABLE VACINA (
    ID_VACINA          NUMBER(10)     DEFAULT SEQ_VACINA.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)     NOT NULL,
    NM_VACINA          VARCHAR2(200)  NOT NULL,
    NR_LOTE            VARCHAR2(50)   NOT NULL,
    DS_FABRICANTE      VARCHAR2(200)  NOT NULL,
    DT_PROXIMA_DOSE    TIMESTAMP,
    DT_CRIACAO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_VACINA        PRIMARY KEY (ID_VACINA),
    CONSTRAINT FK_VACINA_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);

COMMENT ON COLUMN VACINA.DT_PROXIMA_DOSE IS 'Calculado pelo .NET — alimenta lembretes da Luna.';

-- ----------------------------------------------------------------------------
-- PRESCRICAO
-- ----------------------------------------------------------------------------
CREATE TABLE PRESCRICAO (
    ID_PRESCRICAO      NUMBER(10)     DEFAULT SEQ_PRESCRICAO.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)     NOT NULL,
    ID_MEDICAMENTO     NUMBER(10)     NOT NULL,
    DS_POSOLOGIA       VARCHAR2(500)  NOT NULL,
    NR_DURACAO_DIAS    NUMBER(4)      NOT NULL,
    DT_CRIACAO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_PRESCRICAO        PRIMARY KEY (ID_PRESCRICAO),
    CONSTRAINT FK_PRESC_EVENTO      FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT FK_PRESC_MEDICAMENTO FOREIGN KEY (ID_MEDICAMENTO)   REFERENCES MEDICAMENTO(ID_MEDICAMENTO),
    CONSTRAINT CK_PRESC_DURACAO     CHECK (NR_DURACAO_DIAS > 0)
);

-- ----------------------------------------------------------------------------
-- EXAME
-- ----------------------------------------------------------------------------
CREATE TABLE EXAME (
    ID_EXAME           NUMBER(10)     DEFAULT SEQ_EXAME.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)     NOT NULL,
    NM_EXAME           VARCHAR2(200)  NOT NULL,
    DS_RESULTADO       VARCHAR2(1000) NOT NULL,
    DT_REALIZACAO      DATE           NOT NULL,
    DT_CRIACAO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_EXAME        PRIMARY KEY (ID_EXAME),
    CONSTRAINT FK_EXAME_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);

-- ----------------------------------------------------------------------------
-- DOCUMENTO
-- ----------------------------------------------------------------------------
CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO       NUMBER(10)     DEFAULT SEQ_DOCUMENTO.NEXTVAL NOT NULL,
    ID_EVENTO_CLINICO  NUMBER(10)     NOT NULL,
    NM_ARQUIVO         VARCHAR2(200)  NOT NULL,
    DS_TIPO_MIME       VARCHAR2(100)  NOT NULL,
    DS_CAMINHO         VARCHAR2(500)  NOT NULL,
    NR_TAMANHO_BYTES   NUMBER(15)     NOT NULL,
    DT_CRIACAO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO     TIMESTAMP,
    CONSTRAINT PK_DOCUMENTO  PRIMARY KEY (ID_DOCUMENTO),
    CONSTRAINT FK_DOC_EVENTO FOREIGN KEY (ID_EVENTO_CLINICO) REFERENCES EVENTO_CLINICO(ID_EVENTO)
);

CREATE INDEX IDX_DOC_EVENTO ON DOCUMENTO(ID_EVENTO_CLINICO);

COMMENT ON COLUMN DOCUMENTO.DS_CAMINHO IS 'Path no blob storage (Azure Blob / S3) — binário nunca no banco.';

-- ============================================================================
-- 6. NOTIFICAÇÕES — Domínio: .NET
-- ============================================================================

CREATE TABLE NOTIFICACAO (
    ID_NOTIFICACAO  NUMBER(10)     DEFAULT SEQ_NOTIFICACAO.NEXTVAL NOT NULL,
    ID_CLINICA      NUMBER(10)     NOT NULL,
    ID_TUTOR        NUMBER(10),
    ID_VETERINARIO  NUMBER(10),
    DS_TITULO       VARCHAR2(200)  NOT NULL,
    DS_MENSAGEM     VARCHAR2(500)  NOT NULL,
    ST_LIDA         CHAR(1)        DEFAULT 'N' NOT NULL,
    DT_LEITURA      TIMESTAMP,
    DT_CRIACAO      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO  TIMESTAMP,
    CONSTRAINT PK_NOTIFICACAO       PRIMARY KEY (ID_NOTIFICACAO),
    CONSTRAINT FK_NOTIF_CLINICA     FOREIGN KEY (ID_CLINICA)    REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_NOTIF_TUTOR       FOREIGN KEY (ID_TUTOR)      REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_NOTIF_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CK_NOTIF_LIDA        CHECK (ST_LIDA IN ('S','N'))
);

CREATE INDEX IDX_NOTIF_CLINICA ON NOTIFICACAO(ID_CLINICA);
CREATE INDEX IDX_NOTIF_TUTOR   ON NOTIFICACAO(ID_TUTOR);

COMMENT ON TABLE NOTIFICACAO IS 'Notificações in-app e lembretes para tutores e veterinários.';

-- ============================================================================
-- 7. IoT — MONITORAMENTO DE TEMPERATURA — Domínio: .NET
-- ============================================================================

-- ----------------------------------------------------------------------------
-- DISPOSITIVO_IOT — FK CLINICA
-- Autenticação via X-Api-Key no .NET; CD_DISPOSITIVO = MAC/ID do hardware.
-- ----------------------------------------------------------------------------
CREATE TABLE DISPOSITIVO_IOT (
    ID_DISPOSITIVO   NUMBER(10)     DEFAULT SEQ_DISPOSITIVO_IOT.NEXTVAL NOT NULL,
    ID_CLINICA       NUMBER(10)     NOT NULL,
    CD_DISPOSITIVO   VARCHAR2(20)   NOT NULL,
    DS_DESCRICAO     VARCHAR2(500)  NOT NULL,
    DS_LOCALIZACAO   VARCHAR2(500)  NOT NULL,
    DT_CRIACAO       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO   TIMESTAMP,
    CONSTRAINT PK_DISPOSITIVO_IOT    PRIMARY KEY (ID_DISPOSITIVO),
    CONSTRAINT FK_IOT_CLINICA        FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT UK_IOT_CD_DISPOSITIVO UNIQUE (CD_DISPOSITIVO)
);

CREATE INDEX IDX_IOT_CLINICA ON DISPOSITIVO_IOT(ID_CLINICA);

COMMENT ON COLUMN DISPOSITIVO_IOT.CD_DISPOSITIVO IS 'MAC ou ID do ESP32 — autenticação via X-Api-Key no .NET.';

-- ----------------------------------------------------------------------------
-- LEITURA_TEMPERATURA — FK DISPOSITIVO_IOT
-- Time-series: ~1.440 leituras/dia/dispositivo (1 leitura/min).
-- ----------------------------------------------------------------------------
CREATE TABLE LEITURA_TEMPERATURA (
    ID_LEITURA          NUMBER(15)     DEFAULT SEQ_LEITURA_TEMP.NEXTVAL NOT NULL,
    ID_DISPOSITIVO_IOT  NUMBER(10)     NOT NULL,
    VL_TEMPERATURA      NUMBER(5,2)    NOT NULL,
    VL_UMIDADE          NUMBER(5,2),
    DT_LEITURA          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_CRIACAO          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP,
    CONSTRAINT PK_LEITURA_TEMP  PRIMARY KEY (ID_LEITURA),
    CONSTRAINT FK_LEITURA_DISP  FOREIGN KEY (ID_DISPOSITIVO_IOT) REFERENCES DISPOSITIVO_IOT(ID_DISPOSITIVO),
    CONSTRAINT CK_LEITURA_RANGE CHECK (VL_TEMPERATURA BETWEEN -40 AND 80)
);

CREATE INDEX IDX_LEITURA_DISP_DATA ON LEITURA_TEMPERATURA(ID_DISPOSITIVO_IOT, DT_LEITURA DESC);

COMMENT ON TABLE  LEITURA_TEMPERATURA             IS 'Time-series de leituras dos sensores IoT.';
COMMENT ON COLUMN LEITURA_TEMPERATURA.VL_UMIDADE  IS 'Umidade % — opcional (sensores DHT11/DHT22).';

-- ----------------------------------------------------------------------------
-- ALERTA_TEMPERATURA — FK LEITURA_TEMPERATURA
-- Um alerta por evento (não por leitura) — evita poluição no dashboard.
-- ----------------------------------------------------------------------------
CREATE TABLE ALERTA_TEMPERATURA (
    ID_ALERTA              NUMBER(10)     DEFAULT SEQ_ALERTA_TEMP.NEXTVAL NOT NULL,
    ID_LEITURA_TEMPERATURA NUMBER(15)     NOT NULL,
    DS_TIPO_ALERTA         VARCHAR2(50)   NOT NULL,
    VL_LIMITE              NUMBER(5,2)    NOT NULL,
    DS_MENSAGEM            VARCHAR2(500)  NOT NULL,
    ST_RESOLVIDO           CHAR(1)        DEFAULT 'N' NOT NULL,
    DT_CRIACAO             TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO         TIMESTAMP,
    CONSTRAINT PK_ALERTA_TEMP      PRIMARY KEY (ID_ALERTA),
    CONSTRAINT FK_ALERTA_LEITURA   FOREIGN KEY (ID_LEITURA_TEMPERATURA) REFERENCES LEITURA_TEMPERATURA(ID_LEITURA),
    CONSTRAINT CK_ALERTA_RESOLVIDO CHECK (ST_RESOLVIDO IN ('S','N'))
);

CREATE INDEX IDX_ALERTA_LEITURA ON ALERTA_TEMPERATURA(ID_LEITURA_TEMPERATURA);
CREATE INDEX IDX_ALERTA_ATIVOS  ON ALERTA_TEMPERATURA(ST_RESOLVIDO, DT_CRIACAO DESC);

COMMENT ON COLUMN ALERTA_TEMPERATURA.VL_LIMITE    IS 'Limite ultrapassado (°C) — registrado no momento do alerta.';
COMMENT ON COLUMN ALERTA_TEMPERATURA.ST_RESOLVIDO IS 'S = temperatura voltou à faixa e alerta foi fechado.';

-- ============================================================================
-- 8. TRIAGEM LUNA — Domínio: .NET
-- ============================================================================

CREATE TABLE TRIAGEM_LUNA (
    ID_TRIAGEM           NUMBER(10)      DEFAULT SEQ_TRIAGEM_LUNA.NEXTVAL NOT NULL,
    ID_CLINICA           NUMBER(10)      NOT NULL,
    ID_TUTOR             NUMBER(10),
    ID_PET               NUMBER(10),
    DS_NIVEL_URGENCIA    VARCHAR2(20)    NOT NULL,
    DS_DESCRICAO         VARCHAR2(2000)  NOT NULL,
    ST_ENCAMINHADO_VET   CHAR(1)         NOT NULL,
    DT_TRIAGEM           TIMESTAMP       NOT NULL,
    ST_ATIVA             CHAR(1)         DEFAULT 'S' NOT NULL,
    DT_CRIACAO           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO       TIMESTAMP,
    CONSTRAINT PK_TRIAGEM_LUNA     PRIMARY KEY (ID_TRIAGEM),
    CONSTRAINT FK_TRIAGEM_CLINICA  FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_TRIAGEM_TUTOR    FOREIGN KEY (ID_TUTOR)   REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_TRIAGEM_PET      FOREIGN KEY (ID_PET)     REFERENCES PET(ID_PET),
    CONSTRAINT CK_TRIAGEM_ENCAM    CHECK (ST_ENCAMINHADO_VET IN ('S','N')),
    CONSTRAINT CK_TRIAGEM_ATIVA    CHECK (ST_ATIVA           IN ('S','N'))
);

CREATE INDEX IDX_TRIAGEM_CLINICA ON TRIAGEM_LUNA(ID_CLINICA);
CREATE INDEX IDX_TRIAGEM_PET     ON TRIAGEM_LUNA(ID_PET);

COMMENT ON TABLE  TRIAGEM_LUNA                    IS 'Triagens realizadas pela Luna (IA). Tutor/Pet opcionais (sem cadastro).';
COMMENT ON COLUMN TRIAGEM_LUNA.DS_NIVEL_URGENCIA  IS 'BAIXA | MEDIA | ALTA | CRITICA — classificação do bot.';
COMMENT ON COLUMN TRIAGEM_LUNA.ST_ENCAMINHADO_VET IS 'S = bot indicou consulta presencial.';

-- ============================================================================
-- 9. INVITE_TUTOR — Gerado pelo .NET, consumido pelo Java (leitura @Immutable)
-- ============================================================================

CREATE TABLE INVITE_TUTOR (
    ID_INVITE    NUMBER(10)     DEFAULT SEQ_INVITE_TUTOR.NEXTVAL NOT NULL,
    ID_TUTOR     NUMBER(10)     NOT NULL,
    NR_TOKEN     VARCHAR2(36)   NOT NULL,
    DT_EXPIRACAO TIMESTAMP      NOT NULL,
    DS_CANAL     VARCHAR2(20)   NOT NULL,
    ST_UTILIZADO CHAR(1)        DEFAULT 'N' NOT NULL,
    ST_ATIVO     CHAR(1)        DEFAULT 'S' NOT NULL,
    DT_CRIACAO   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO TIMESTAMP,
    CONSTRAINT PK_INVITE_TUTOR  PRIMARY KEY (ID_INVITE),
    CONSTRAINT FK_INVITE_TUTOR  FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE,
    CONSTRAINT UK_INVITE_TOKEN  UNIQUE (NR_TOKEN),
    CONSTRAINT CK_INVITE_CANAL  CHECK (DS_CANAL      IN ('WHATSAPP','EMAIL','SMS')),
    CONSTRAINT CK_INVITE_UTILIZ CHECK (ST_UTILIZADO  IN ('S','N')),
    CONSTRAINT CK_INVITE_ATIVO  CHECK (ST_ATIVO      IN ('S','N'))
);

-- IDX_INVITE_TOKEN_ATIVO: filtro composto — InviteTutorRepository.findByNrToken(...)
-- WHERE NR_TOKEN = ? AND ST_UTILIZADO = 'N' AND ST_ATIVO = 'S'
CREATE INDEX IDX_INVITE_TUTOR       ON INVITE_TUTOR(ID_TUTOR);
CREATE INDEX IDX_INVITE_TOKEN_ATIVO ON INVITE_TUTOR(NR_TOKEN, ST_UTILIZADO, ST_ATIVO);

COMMENT ON TABLE  INVITE_TUTOR              IS 'Convite de onboarding: .NET gera UUID, Java valida e consome 1x.';
COMMENT ON COLUMN INVITE_TUTOR.NR_TOKEN     IS 'UUID v4 (36 chars) gerado com SecureRandom — enviado ao tutor.';
COMMENT ON COLUMN INVITE_TUTOR.ST_UTILIZADO IS 'S = invite consumido; UK_CONTA_INVITE_USED impede reutilização.';
COMMENT ON COLUMN INVITE_TUTOR.ST_ATIVO     IS 'N = expirado ou revogado (soft delete).';

-- ============================================================================
-- 10. DOMÍNIO JAVA — Tabelas escritas exclusivamente pelo Backend Tutor (Java)
-- PK: GENERATED BY DEFAULT AS IDENTITY (Oracle 19c, compatível com
--     GenerationType.IDENTITY do JPA/Hibernate 6)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CONTA_TUTOR — Credenciais de acesso ao portal do tutor
-- ATENÇÃO: DT_CRIACAO (não DT_CADASTRO) — conforme @Column na entity Java.
-- ----------------------------------------------------------------------------
CREATE TABLE CONTA_TUTOR (
    ID_CONTA              NUMBER(10)     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_TUTOR              NUMBER(10)     NOT NULL,
    DS_EMAIL_LOGIN        VARCHAR2(120)  NOT NULL,
    DS_SENHA_HASH         VARCHAR2(256)  NOT NULL,
    ID_INVITE_USADO       NUMBER(10),
    DS_REFRESH_TOKEN_HASH VARCHAR2(256),
    DT_REFRESH_EXPIRA     TIMESTAMP,
    DT_CRIACAO            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ULTIMO_LOGIN       TIMESTAMP,
    NR_TENTATIVAS_LOGIN   NUMBER(2)      DEFAULT 0 NOT NULL,
    DT_BLOQUEIO           TIMESTAMP,
    ST_ATIVA              CHAR(1)        DEFAULT 'S' NOT NULL,
    ST_EMAIL_VERIFICADO   CHAR(1)        DEFAULT 'N' NOT NULL,
    DS_TOKEN_RESET        VARCHAR2(256),
    DT_TOKEN_EXPIRA       TIMESTAMP,
    CONSTRAINT PK_CONTA_TUTOR        PRIMARY KEY (ID_CONTA),
    CONSTRAINT FK_CONTA_TUTOR        FOREIGN KEY (ID_TUTOR)        REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_CONTA_INVITE       FOREIGN KEY (ID_INVITE_USADO) REFERENCES INVITE_TUTOR(ID_INVITE),
    CONSTRAINT UK_CONTA_TUTOR_EMAIL  UNIQUE (DS_EMAIL_LOGIN),
    CONSTRAINT UK_CONTA_TUTOR_TUTOR  UNIQUE (ID_TUTOR),
    CONSTRAINT UK_CONTA_INVITE_USED  UNIQUE (ID_INVITE_USADO),
    CONSTRAINT CK_CONTA_ATIVA        CHECK (ST_ATIVA           IN ('S','N')),
    CONSTRAINT CK_CONTA_EMAIL_VERIF  CHECK (ST_EMAIL_VERIFICADO IN ('S','N')),
    CONSTRAINT CK_CONTA_TENTATIVAS   CHECK (NR_TENTATIVAS_LOGIN BETWEEN 0 AND 99)
);

COMMENT ON TABLE  CONTA_TUTOR                       IS 'Credenciais de acesso ao portal. Exclusivo do Backend Java.';
COMMENT ON COLUMN CONTA_TUTOR.DS_SENHA_HASH         IS 'BCrypt — NUNCA texto plano.';
COMMENT ON COLUMN CONTA_TUTOR.DS_REFRESH_TOKEN_HASH IS 'BCrypt do refresh token — rotacionado a cada login/refresh.';
COMMENT ON COLUMN CONTA_TUTOR.ID_INVITE_USADO       IS 'UK_CONTA_INVITE_USED: 1 invite = 1 conta. Race condition → ORA-00001 → HTTP 409.';
COMMENT ON COLUMN CONTA_TUTOR.NR_TENTATIVAS_LOGIN   IS 'Bloqueio automático (HTTP 423) após 5 falhas consecutivas.';

-- ----------------------------------------------------------------------------
-- CONSENTIMENTO — Registro LGPD (somente INSERT, nunca UPDATE)
-- DT_ACEITE (não DT_CONSENTIMENTO), DS_VERSAO_TERMO (não NR_VERSAO_TERMO) —
-- conforme @Column da entity Java e requisito LGPD art. 7º, I.
-- ----------------------------------------------------------------------------
CREATE TABLE CONSENTIMENTO (
    ID_CONSENTIMENTO  NUMBER(10)     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_TUTOR          NUMBER(10)     NOT NULL,
    DS_TIPO           VARCHAR2(40)   NOT NULL,
    DS_VERSAO_TERMO   VARCHAR2(20)   NOT NULL,
    DS_TEXTO_TERMO    CLOB,
    ST_ACEITO         CHAR(1)        NOT NULL,
    DT_ACEITE         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DS_IP_ACEITE      VARCHAR2(45),
    DT_REVOGACAO      TIMESTAMP,
    DS_IP_REVOGACAO   VARCHAR2(45),
    CONSTRAINT PK_CONSENTIMENTO   PRIMARY KEY (ID_CONSENTIMENTO),
    CONSTRAINT FK_CONS_TUTOR      FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT CK_CONS_TIPO       CHECK (DS_TIPO IN (
        'TELEORIENTACAO','LEMBRETES','DADOS_ANONIMOS','COMPARTILHAR_SEGURADORA','MARKETING'
    )),
    CONSTRAINT CK_CONS_ACEITO     CHECK (ST_ACEITO IN ('S','N'))
);

CREATE INDEX IDX_CONS_TUTOR ON CONSENTIMENTO(ID_TUTOR, DS_TIPO);

COMMENT ON TABLE  CONSENTIMENTO                IS 'Histórico LGPD. Cada aceite/revogação = nova linha — somente INSERT.';
COMMENT ON COLUMN CONSENTIMENTO.DS_TEXTO_TERMO IS 'Snapshot do texto no momento do aceite — evidência ANPD (LGPD art. 7º, I).';
COMMENT ON COLUMN CONSENTIMENTO.DS_IP_ACEITE   IS 'IP do cliente (X-Forwarded-For) — evidência legal.';

-- ----------------------------------------------------------------------------
-- AGENDAMENTO — Shared-write: Java cria/edita/cancela; .NET atualiza ST_STATUS.
-- PK via SEQ_AGENDAMENTO (Java usa GenerationType.SEQUENCE).
-- DS_TIPO = tipo de consulta (Java entity: @Column name="DS_TIPO").
-- ----------------------------------------------------------------------------
CREATE TABLE AGENDAMENTO (
    ID_AGENDAMENTO      NUMBER(10)     DEFAULT SEQ_AGENDAMENTO.NEXTVAL NOT NULL,
    ID_CLINICA          NUMBER(10)     NOT NULL,
    ID_TUTOR            NUMBER(10),
    ID_PET              NUMBER(10),
    ID_VETERINARIO      NUMBER(10),
    NM_PACIENTE         VARCHAR2(200),
    DS_SERVICO          VARCHAR2(200),
    DT_AGENDAMENTO      TIMESTAMP      NOT NULL,
    NR_DURACAO_MINUTOS  NUMBER(4)      DEFAULT 30,
    ST_STATUS           VARCHAR2(50)   DEFAULT 'AGENDADO' NOT NULL,
    DS_TIPO             VARCHAR2(30),
    DS_ORIGEM           VARCHAR2(100)  DEFAULT 'PORTAL',
    DS_OBSERVACOES      VARCHAR2(1000),
    DT_CRIACAO          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_CONFIRMACAO      TIMESTAMP,
    DT_CANCELAMENTO     TIMESTAMP,
    DS_MOTIVO_CANCEL    VARCHAR2(500),
    ID_EVENTO_GERADO    NUMBER(10),
    NR_VERSION          NUMBER(10)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_AGENDAMENTO       PRIMARY KEY (ID_AGENDAMENTO),
    CONSTRAINT FK_AGEND_CLINICA     FOREIGN KEY (ID_CLINICA)     REFERENCES CLINICA(ID_CLINICA),
    CONSTRAINT FK_AGEND_TUTOR       FOREIGN KEY (ID_TUTOR)       REFERENCES TUTOR(ID_TUTOR),
    CONSTRAINT FK_AGEND_PET         FOREIGN KEY (ID_PET)         REFERENCES PET(ID_PET),
    CONSTRAINT FK_AGEND_VET         FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT FK_AGEND_EVENTO      FOREIGN KEY (ID_EVENTO_GERADO) REFERENCES EVENTO_CLINICO(ID_EVENTO),
    CONSTRAINT CK_AGEND_STATUS      CHECK (ST_STATUS IN (
        'INTENCAO','AGENDADO','CONFIRMADO','REALIZADO','CANCELADO','NAO_COMPARECEU'
    )),
    CONSTRAINT CK_AGEND_VERSION     CHECK (NR_VERSION >= 0)
);

CREATE INDEX IDX_AGEND_CLINICA ON AGENDAMENTO(ID_CLINICA);
CREATE INDEX IDX_AGEND_TUTOR   ON AGENDAMENTO(ID_TUTOR);
CREATE INDEX IDX_AGEND_PET     ON AGENDAMENTO(ID_PET);
CREATE INDEX IDX_AGEND_DATA    ON AGENDAMENTO(DT_AGENDAMENTO);
CREATE INDEX IDX_AGEND_STATUS  ON AGENDAMENTO(ST_STATUS);
CREATE INDEX IDX_AGEND_EVENTO  ON AGENDAMENTO(ID_EVENTO_GERADO);

COMMENT ON TABLE  AGENDAMENTO              IS 'Shared-write: Java cria/edita/cancela; .NET atualiza ST_STATUS via PATCH.';
COMMENT ON COLUMN AGENDAMENTO.DS_TIPO      IS 'Tipo da consulta (ex: VACINA, CONSULTA) — Java entity: dsTipoConsulta.';
COMMENT ON COLUMN AGENDAMENTO.NR_VERSION   IS 'Optimistic locking @Version — sincroniza Java POST/PUT com .NET PATCH → HTTP 409.';
COMMENT ON COLUMN AGENDAMENTO.ID_EVENTO_GERADO IS '.NET preenche quando ST_STATUS=REALIZADO com o ID_EVENTO_CLINICO gerado.';
COMMENT ON COLUMN AGENDAMENTO.NM_PACIENTE  IS 'Snapshot do nome do pet ao criar — denormalizado para exibição.';

-- ----------------------------------------------------------------------------
-- IDEMPOTENCY_KEY — Exactly-once para POSTs sensíveis (CONSENTIMENTO)
-- TTL 24h — limpeza via job agendado.
-- ----------------------------------------------------------------------------
CREATE TABLE IDEMPOTENCY_KEY (
    ID_IDEMPOTENCY      NUMBER(10)     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DS_KEY              VARCHAR2(64)   NOT NULL,
    NM_RESOURCE         VARCHAR2(60)   NOT NULL,
    ID_RESOURCE_CRIADO  NUMBER(10)     NOT NULL,
    DT_CRIACAO          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DT_EXPIRACAO        TIMESTAMP      NOT NULL,
    CONSTRAINT PK_IDEMPOTENCY_KEY   PRIMARY KEY (ID_IDEMPOTENCY),
    CONSTRAINT UK_IDEM_KEY_RESOURCE UNIQUE (DS_KEY, NM_RESOURCE),
    CONSTRAINT CK_IDEMPOT_EXPIRA    CHECK (DT_EXPIRACAO > DT_CRIACAO)
);

-- IDX_IDEMPOT_EXPIRA: limpeza TTL (job: DELETE WHERE DT_EXPIRACAO < SYSDATE)
-- IDX_IDEMPOT_CRIACAO: limpeza alternativa por criação (Flyway V2)
CREATE INDEX IDX_IDEMPOT_EXPIRA  ON IDEMPOTENCY_KEY(DT_EXPIRACAO);
CREATE INDEX IDX_IDEMPOT_CRIACAO ON IDEMPOTENCY_KEY(DT_CRIACAO);

COMMENT ON TABLE  IDEMPOTENCY_KEY                  IS 'Exactly-once para POSTs sensíveis (CONSENTIMENTO). TTL 24h.';
COMMENT ON COLUMN IDEMPOTENCY_KEY.DS_KEY           IS 'UUID v4 enviado pelo cliente via header Idempotency-Key.';
COMMENT ON COLUMN IDEMPOTENCY_KEY.NM_RESOURCE      IS 'Recurso alvo (ex: CONSENTIMENTO, AGENDAMENTO).';
COMMENT ON COLUMN IDEMPOTENCY_KEY.ID_RESOURCE_CRIADO IS 'PK do registro criado — retornado em chamadas duplicadas sem reprocessar.';

-- ============================================================================
-- 11. AUDITORIA
-- ============================================================================

-- ----------------------------------------------------------------------------
-- LOG_ERRO — Java escreve via EXCEPTION WHEN OTHERS das procedures Oracle.
-- Sem FKs: log de erro nunca deve falhar por violação referencial.
-- ----------------------------------------------------------------------------
CREATE TABLE LOG_ERRO (
    ID_LOG            NUMBER(15)     DEFAULT SEQ_LOG_ERRO.NEXTVAL NOT NULL,
    NM_PROCEDURE      VARCHAR2(120)  NOT NULL,
    NM_USUARIO        VARCHAR2(60)   NOT NULL,
    DT_ERRO           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    NR_CODIGO_ERRO    NUMBER(10)     NOT NULL,
    DS_MENSAGEM_ERRO  VARCHAR2(2000) NOT NULL,
    DS_PARAMETROS     VARCHAR2(2000),
    DS_STACK_TRACE    CLOB,
    CONSTRAINT PK_LOG_ERRO PRIMARY KEY (ID_LOG)
);

CREATE INDEX IDX_LOG_DATA      ON LOG_ERRO(DT_ERRO DESC);
CREATE INDEX IDX_LOG_PROCEDURE ON LOG_ERRO(NM_PROCEDURE);

COMMENT ON TABLE LOG_ERRO IS 'Log de erros de procedures Oracle (requisito FIAP — disciplina BD). .NET usa ILogger estruturado.';

-- ============================================================================
-- 12. VIEWS
-- Definição final após Flyway V6: baseadas em AGENDAMENTO para uso do Java.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- VW_TIMELINE_PET — lida pelo Java TimelineService
-- Aliases V6: ID_AGENDAMENTO→ID_EVENTO, DT_AGENDAMENTO→DT_EVENTO
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_TIMELINE_PET AS
SELECT
    a.ID_PET,
    a.ID_AGENDAMENTO  AS ID_EVENTO,
    p.NM_PET,
    a.DT_AGENDAMENTO  AS DT_EVENTO,
    a.DS_TIPO         AS DS_TIPO_EVENTO,
    a.ST_STATUS,
    a.ID_CLINICA,
    c.NM_CLINICA
FROM   AGENDAMENTO  a
JOIN   PET          p ON p.ID_PET     = a.ID_PET
JOIN   CLINICA      c ON c.ID_CLINICA = a.ID_CLINICA
WHERE  a.ID_PET IS NOT NULL;

COMMENT ON TABLE VW_TIMELINE_PET IS 'Linha do tempo de atendimentos por pet — lida pelo Java TimelineService.';

-- ----------------------------------------------------------------------------
-- VW_VACINAS_VENCENDO — alertas preventivos Luna (próximos 30 dias)
-- DS_TIPO AS NM_VACINA, DT_AGENDAMENTO AS DT_PROXIMA_DOSE (alias V6)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_VACINAS_VENCENDO AS
SELECT
    p.ID_PET,
    p.NM_PET,
    a.ID_TUTOR,
    a.DS_TIPO         AS NM_VACINA,
    a.DT_AGENDAMENTO  AS DT_PROXIMA_DOSE,
    a.ID_CLINICA,
    c.NM_CLINICA
FROM   AGENDAMENTO  a
JOIN   PET          p ON p.ID_PET     = a.ID_PET
JOIN   CLINICA      c ON c.ID_CLINICA = a.ID_CLINICA
WHERE  a.DS_TIPO   = 'VACINA'
  AND  a.ST_STATUS NOT IN ('CANCELADO','REALIZADO')
  AND  a.DT_AGENDAMENTO >= SYSTIMESTAMP
  AND  a.DT_AGENDAMENTO <= SYSTIMESTAMP + INTERVAL '30' DAY;

COMMENT ON TABLE VW_VACINAS_VENCENDO IS 'Vacinas agendadas nos próximos 30 dias — alimenta alertas preventivos da Luna.';

-- ----------------------------------------------------------------------------
-- VW_TIMELINE_CLINICA — eventos clínicos completos (.NET e Luna)
-- Fonte: EVENTO_CLINICO (escrita .NET) — separada da timeline AGENDAMENTO.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_TIMELINE_CLINICA AS
SELECT
    p.ID_PET,
    p.NM_PET,
    e.ID_EVENTO,
    te.NM_TIPO         AS NM_TIPO_EVENTO,
    te.CD_TIPO         AS CD_TIPO_EVENTO,
    e.DT_EVENTO,
    v.NM_VETERINARIO,
    e.DS_OBSERVACAO,
    c.NM_CLINICA
FROM   PET           p
JOIN   EVENTO_CLINICO e  ON e.ID_PET         = p.ID_PET
JOIN   VETERINARIO    v  ON v.ID_VETERINARIO = e.ID_VETERINARIO
JOIN   TIPO_EVENTO   te  ON te.ID_TIPO_EVENTO = e.ID_TIPO_EVENTO
JOIN   CLINICA        c  ON c.ID_CLINICA      = e.ID_CLINICA
WHERE  p.ST_ATIVO = 'S';

COMMENT ON TABLE VW_TIMELINE_CLINICA IS 'Timeline clínica completa por pet (eventos EVENTO_CLINICO do .NET). Separada da VW_TIMELINE_PET.';

-- ============================================================================
-- FIM DA DDL — kura_schema_v5.sql
-- ============================================================================
-- RESUMO DAS ALTERAÇÕES (v4 → v5):
--
--   Sequences adicionadas : nenhuma (mesmas do v4)
--   Tabelas novas         : nenhuma
--
--   Tabelas Java modificadas:
--     CONTA_TUTOR     → DT_CRIACAO (era DT_CADASTRO); sem DS_SALT
--                        UK_CONTA_INVITE_USED inline
--     CONSENTIMENTO   → DT_ACEITE (era DT_CONSENTIMENTO); DS_VERSAO_TERMO;
--                        campos LGPD: DS_TEXTO_TERMO, DS_IP_ACEITE,
--                        DT_REVOGACAO, DS_IP_REVOGACAO
--     AGENDAMENTO     → campos V5 Flyway: DS_OBSERVACOES, DT_CRIACAO,
--                        DT_CONFIRMACAO, DT_CANCELAMENTO, DS_MOTIVO_CANCEL,
--                        ID_EVENTO_GERADO + FK_AGEND_EVENTO
--     IDEMPOTENCY_KEY → IDX_IDEMPOT_CRIACAO inline (era V2 Flyway)
--
--   Tabelas .NET modificadas:
--     TUTOR  → DS_TELEFONE (era NR_TELEFONE), DT_CADASTRO (era DT_CRIACAO)
--     RACA   → DS_PREDISPOSICAO incluída
--     PET    → campos legados removidos (NR_PESO_KG, ST_CASTRADO etc.)
--     INVITE_TUTOR → IDX_INVITE_TOKEN_ATIVO inline (era V3 Flyway)
--
--   Views:
--     VW_TIMELINE_PET     → alias V6 (ID_EVENTO, DT_EVENTO)
--     VW_VACINAS_VENCENDO → alias V6 (NM_VACINA, DT_PROXIMA_DOSE)
--     VW_TIMELINE_CLINICA → NOVA — timeline clínica .NET via EVENTO_CLINICO
-- ============================================================================
